class CfgPatches
{
	class CQB_Interactions
	{
		units[]={};
		weapons[]={};
		requiredAddons[]=
		{
			"cba_main",
			"cba_common"
		};
		author="Flex7103, Phenosi";
		authorUrl="";
		version="1.1.1";
		versionStr="1.1.1";
		versionAr[]={1,1,1};
	};
};
class Extended_PreInit_EventHandlers
{
	class CQB_Interactions_PreInit
	{
		init="call compile preprocessFileLineNumbers 'CQB_Interactions\Bootstrap\XEH_preInit.sqf'";
	};
};
class Extended_PostInit_EventHandlers
{
	class CQB_Interactions_PostInit
	{
		init="call compile preprocessFileLineNumbers 'CQB_Interactions\Bootstrap\XEH_postInit.sqf'";
	};
};
class cfg3Den
{
	class Object
	{
		class AttributeCategories
		{
			class StateSpecial
			{
				class Attributes
				{
					class CQB_Interations_IsDisableMoraleSystem
					{
						displayName="Disable Morale System";
						tooltip="Disable Morale System for unit?";
						property="CQB_Interations_DisabledMoraleSystem";
						control="Checkbox";
						defaultValue="false";
						expression="if (_value) then {[_this, true] call CQB_Interactions_Fnc_DisableMoraleSystem}";
						condition="objectControllable";
					};
				};
			};
		};
	};
};
class CfgMovesBasic
{
	class default;
	class DefaultDie;
	class ManActions
	{
		AnimCableStandStart[]=
		{
			"AnimCableStandStart",
			"gesture"
		};
		AnimCableStandLoop[]=
		{
			"AnimCableStandLoop",
			"gesture"
		};
		AnimCableStandEnd[]=
		{
			"AnimCableStandEnd",
			"gesture"
		};
		AnimExecuteKneelStart[]=
		{
			"AnimExecuteKneelStart",
			"gesture"
		};
		AnimExecuteKneelLoop[]=
		{
			"AnimExecuteKneelLoop",
			"gesture"
		};
		AnimExecuteKneelEnd[]=
		{
			"AnimExecuteKneelEnd",
			"gesture"
		};
		AnimExecuteStandStart[]=
		{
			"AnimExecuteStandStart",
			"gesture"
		};
		AnimExecuteStandLoop[]=
		{
			"AnimExecuteStandLoop",
			"gesture"
		};
		AnimExecuteStandEnd[]=
		{
			"AnimExecuteStandEnd",
			"gesture"
		};
		AnimRunJump[]=
		{
			"AnimRunJump",
			"gesture"
		};
		AnimJumpOver[]=
		{
			"AnimJumpOver",
			"gesture"
		};
		AnimWaitWall[]=
		{
			"AnimWaitWall",
			"gesture"
		};
		AnimHoldShotgun[]=
		{
			"AnimHoldShotgun",
			"gesture"
		};
		AnimStandSniper[]=
		{
			"AnimStandSniper",
			"gesture"
		};
		AnimHCAction[]=
		{
			"AnimHCAction",
			"gesture"
		};
		AnimShottie[]=
		{
			"AnimShottie",
			"gesture"
		};
		AnimDropdown[]=
		{
			"AnimDropdown",
			"gesture"
		};
		AnimHangShotgun[]=
		{
			"AnimHangShotgun",
			"gesture"
		};
		AnimInspectAssaultrifle[]=
		{
			"AnimInspectAssaultrifle",
			"gesture"
		};
		AnimGoForwardRifle[]=
		{
			"AnimGoForwardRifle",
			"gesture"
		};
		AnimGoForwardHandgun[]=
		{
			"AnimGoForwardHandgun",
			"gesture"
		};
		AnimInspectHandgun[]=
		{
			"AnimInspectHandgun",
			"gesture"
		};
		AnimStandHoldSniper[]=
		{
			"AnimStandHoldSniper",
			"gesture"
		};
		AnimStabKnife[]=
		{
			"AnimStabKnife",
			"gesture"
		};
		AnimSlashKnife[]=
		{
			"AnimSlashKnife",
			"gesture"
		};
	};
};
class CfgGesturesMale
{
	class default;
	class States
	{
		class AnimCableStandStart: default
		{
			file="CQB_Interactions\anims\anim_cable_stand_start.rtm";
			speed=1;
			looped=0;
			mask="handsWeapon_pst";
		};
		class AnimCableStandLoop: AnimCableStandStart
		{
			file="CQB_Interactions\anims\anim_cable_stand_loop.rtm";
			speed=0.059999999;
			looped=1;
		};
		class AnimCableStandEnd: AnimCableStandStart
		{
			file="CQB_Interactions\anims\anim_cable_stand_end.rtm";
		};
		class AnimExecuteKneelStart: default
		{
			file="CQB_Interactions\anims\anim_execute_kneel_start.rtm";
			speed=0.5;
			looped=0;
			mask="BodyFullRealNoWeapon";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0,1,0.0099999998,0,0.99000001,0,1,1};
		};
		class AnimStabKnife: default
		{
			file="CQB_Interactions\anims\anim_stab_knife.rtm";
			speed=-1.2;
			looped=0;
			mask="handsWeapon";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0,1,0.050000001,1,0.1,0,0.89999998,0,0.94999999,1,1,1};
		};
		class AnimSlashKnife: AnimStabKnife
		{
			file="CQB_Interactions\anims\anim_slash_knife.rtm";
			speed=-1.2;
		};
		class AnimExecuteKneelLoop: AnimExecuteKneelStart
		{
			file="CQB_Interactions\anims\anim_execute_kneel_loop.rtm";
			speed=0.1;
			looped=1;
			duty=-0.30000001;
			interpolationSpeed=6.0500002;
			canPullTrigger=1;
			disableWeapons=0;
			canReload=0;
			limitGunMovement=0.15000001;
			showWeaponAim=0;
			showHandGun=1;
			aimingBody="aimingUpDefault";
			aiming="aimingDefault";
			aimPrecision=4;
			headBobStrength=0.2;
			headBobMode=2;
			weaponLowered=0;
		};
		class AnimExecuteKneelEnd: AnimExecuteKneelStart
		{
			file="CQB_Interactions\anims\anim_execute_kneel_end.rtm";
		};
		class AnimExecuteStandStart: default
		{
			file="CQB_Interactions\anims\anim_execute_stand_start.rtm";
			speed=0.69999999;
			looped=0;
			mask="BodyFullRealNoWeapon";
			rightHandIKCurve[]={0,1,0.0099999998,0,0.99000001,0,1,1};
			leftHandIKCurve[]={0,1,0.0099999998,0,0.99000001,0,1,1};
		};
		class AnimExecuteStandLoop: AnimExecuteStandStart
		{
			file="CQB_Interactions\anims\anim_execute_stand_loop.rtm";
			speed=0.1;
			looped=1;
			duty=-0.30000001;
			interpolationSpeed=6.0500002;
			canPullTrigger=1;
			disableWeapons=0;
			canReload=0;
			limitGunMovement=0.15000001;
			showWeaponAim=0;
			showHandGun=1;
			aimingBody="aimingUpDefault";
			aiming="aimingDefault";
			aimPrecision=4;
			headBobStrength=0.2;
			headBobMode=2;
			weaponLowered=0;
		};
		class AnimExecuteStandEnd: AnimExecuteStandStart
		{
			file="CQB_Interactions\anims\anim_execute_stand_end.rtm";
		};
		class AnimRunJump: default
		{
			file="CQB_Interactions\anims\anim_run_jump.rtm";
			speed=0.89999998;
			looped=0;
			mask="BodyFull";
			disableWeapons=0;
			headBobMode=2;
			headBobStrength=0.2;
			interpolationSpeed=6.0500002;
			canPullTrigger=1;
			weaponLowered=0;
		};
		class AnimStandHoldSniper: default
		{
			file="CQB_Interactions\anims\anim_stand_hold_sniper.rtm";
			speed=1;
			looped=1;
			rightHandIKCurve[]={0};
			leftHandIKCurve[]={0};
			canPullTrigger=0;
			mask="BodyFullReal";
		};
		class AnimHCAction: default
		{
			file="CQB_Interactions\anims\anim_hcaction.rtm";
			speed=1;
			looped=1;
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
			canPullTrigger=0;
			mask="BodyFullReal";
		};
		class AnimShottie: default
		{
			file="CQB_Interactions\anims\anim_shottie.rtm";
			speed=1;
			looped=1;
			rightHandIKCurve[]={0};
			leftHandIKCurve[]={0};
			canPullTrigger=0;
			mask="BodyFullReal";
		};
		class AnimDropdown: default
		{
			file="CQB_Interactions\anims\anim_dropdown.rtm";
			speed=1;
			looped=1;
			rightHandIKCurve[]={0};
			leftHandIKCurve[]={1};
			canPullTrigger=0;
			mask="BodyFullReal";
		};
		class AnimInspectAssaultrifle: default
		{
			file="CQB_Interactions\anims\anim_inspect_assaultrifle.rtm";
			looped=0;
			speed=0.23;
			mask="handsWeapon";
			headBobStrength=0.2;
			headBobMode=2;
			canPullTrigger=0;
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0,1,0.44999999,1,0.5,0,0.94999999,0,0.98000002,1,1,1};
		};
		class AnimGoForwardRifle: default
		{
			file="CQB_Interactions\anims\anim_go_forward.rtm";
			looped=0;
			speed=-2.5;
			mask="handsWeapon";
			headBobStrength=0.2;
			headBobMode=2;
			canPullTrigger=0;
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0.02,1,0.050000001,0,0.94999999,0,0.98000002,1};
		};
		class AnimGoForwardHandgun: AnimGoForwardRifle
		{
			mask="handsWeapon_pst";
		};
		class AnimInspectHandgun: default
		{
			file="CQB_Interactions\anims\anim_inspect_handgun.rtm";
			looped=0;
			speed=0.23;
			mask="handsWeapon_pst";
			headBobStrength=0.2;
			headBobMode=2;
			canPullTrigger=0;
			rightHandIKCurve[]={0};
			leftHandIKCurve[]={0};
		};
	};
	class BlendAnims
	{
		class MaskStart
		{
			weight=0.85000002;
		};
		class MaskStartDecreased
		{
			weight=0.34999999;
		};
		empty[]={};
		BodyFullRealNoWeapon[]=
		{
			"head",
			1,
			"neck1",
			1,
			"neck",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"Spine1",
			1,
			"Spine2",
			1,
			"Spine3",
			1,
			"Spine",
			1,
			"Pelvis",
			1,
			"LeftLeg",
			1,
			"LeftLegRoll",
			1,
			"LeftUpLeg",
			1,
			"LeftUpLegRoll",
			1,
			"LeftFoot",
			1,
			"LeftToeBase",
			1,
			"RightLeg",
			1,
			"RightLegRoll",
			1,
			"RightUpLeg",
			1,
			"RightUpLegRoll",
			1,
			"RightFoot",
			1,
			"RightToeBase",
			1
		};
	};
};
class CfgMovesMaleSdr: CfgMovesBasic
{
	skeletonName="OFP2_ManSkeleton";
	gestures="CfgGesturesMale";
	access=1;
	class States
	{
		class DeadState;
		class AnimWeaponSurrender: default
		{
			file="CQB_Interactions\anims\anim_weapon_surrender.rtm";
			speed=1.5;
			looped=0;
			duty=2;
			mask="BodyFullReal";
			enableDirectControl=0;
			leftHandIKCurve[]={0};
			RightHandIKCurve[]={0};
			weaponIK=0;
			forceAim=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			disableWeapons=1;
			disableWeaponsLong=1;
			headBobMode=1;
			headBobStrength=0.2;
			canPullTrigger=0;
			showHandGun=0;
			showItemInRightHand=0;
			variantsPlayer[]={};
			variantsAI[]={};
			weaponLowered=0;
		};
		class AnimWeaponSurrenderLoop: AnimWeaponSurrender
		{
			file="CQB_Interactions\anims\anim_weapon_surrender_loop.rtm";
			speed=0.1;
			looped=1;
			ConnectTo[]=
			{
				"BasicDriverDead",
				1
			};
			InterpolateTo[]=
			{
				"BasicDriverDead",
				0.1
			};
		};
		class AnimWeaponSurrenderDrop: default
		{
			file="CQB_Interactions\anims\anim_weapon_surrender_drop.rtm";
			speed=1.5;
			looped=0;
			duty=2;
			mask="BodyFullReal";
			enableDirectControl=0;
			leftHandIKCurve[]={0};
			RightHandIKCurve[]={0};
			weaponIK=0;
			forceAim=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			disableWeapons=1;
			disableWeaponsLong=1;
			headBobMode=1;
			headBobStrength=0.2;
			canPullTrigger=0;
			showHandGun=0;
			showItemInRightHand=0;
			variantsPlayer[]={};
			variantsAI[]={};
			weaponLowered=0;
		};
		class AnimNoWeaponSurrenderLoop: AnimWeaponSurrenderDrop
		{
			file="CQB_Interactions\anims\anim_no_weapon_surrender_loop.rtm";
			speed=0.1;
			looped=1;
			ConnectTo[]=
			{
				"BasicDriverDead",
				1
			};
			InterpolateTo[]=
			{
				"BasicDriverDead",
				0.1
			};
		};
		class AnimCableCrouchStart: default
		{
			file="CQB_Interactions\anims\anim_cable_crouch_start.rtm";
			looped=0;
			speed=1;
			duty=2;
			mask="BodyFullReal";
			enableDirectControl=0;
			leftHandIKCurve[]={0};
			RightHandIKCurve[]={0};
			weaponIK=0;
			forceAim=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			disableWeapons=1;
			disableWeaponsLong=1;
			headBobMode=1;
			headBobStrength=0.2;
			canPullTrigger=0;
			showHandGun=0;
			showItemInRightHand=0;
			variantsPlayer[]={};
			variantsAI[]={};
			weaponLowered=0;
		};
		class AnimCableCrouchLoop: AnimCableCrouchStart
		{
			file="CQB_Interactions\anims\anim_cable_crouch_loop.rtm";
			looped=1;
			speed=0.1;
			ConnectTo[]=
			{
				"BasicDriverDead",
				1
			};
			InterpolateTo[]=
			{
				"BasicDriverDead",
				0.1
			};
		};
		class AnimCableCrouchToStand: AnimCableCrouchStart
		{
			file="CQB_Interactions\anims\anim_cable_crouch_to_stand.rtm";
		};
		class AnimTakedownStandStart: default
		{
			file="CQB_Interactions\anims\anim_takedown_stand.rtm";
			looped=0;
			speed=1;
			duty=2;
			mask="BodyFull";
			enableDirectControl=0;
			leftHandIKCurve[]={0};
			RightHandIKCurve[]={0,1,0.22,1,0.23999999,0,1,0};
			weaponIK=0;
			forceAim=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			disableWeapons=1;
			disableWeaponsLong=1;
			headBobMode=1;
			headBobStrength=0.2;
			canPullTrigger=0;
			showHandGun=0;
			showItemInRightHand=0;
			variantsPlayer[]={};
			variantsAI[]={};
			weaponLowered=0;
		};
		class AnimTakedownStandLoop: AnimTakedownStandStart
		{
			file="CQB_Interactions\anims\anim_takedown_stand_loop.rtm";
			speed=0.5;
			looped=1;
			RightHandIKCurve[]={0};
			ConnectTo[]=
			{
				"BasicDriverDead",
				1
			};
			InterpolateTo[]=
			{
				"BasicDriverDead",
				0.1
			};
		};
		class AnimTakedownStandEnd: AnimTakedownStandStart
		{
			file="CQB_Interactions\anims\anim_takedown_stand_end.rtm";
			RightHandIKCurve[]={0,0,0.56,0,0.57999998,1,1,1};
		};
		class AnimTakendownStandStart: default
		{
			file="CQB_Interactions\anims\anim_takendown_stand.rtm";
			looped=0;
			speed=1;
			mask="BodyFull";
			enableDirectControl=0;
			leftHandIKCurve[]={0};
			RightHandIKCurve[]={0};
			weaponIK=0;
			forceAim=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			disableWeapons=1;
			disableWeaponsLong=1;
			headBobMode=1;
			headBobStrength=0.2;
			canPullTrigger=0;
			showHandGun=0;
			showItemInRightHand=0;
			skeletonName="OFP2_ManSkeleton";
			variantsPlayer[]={};
			variantsAI[]={};
			weaponLowered=0;
		};
		class AnimTakendownStandLoop: AnimTakendownStandStart
		{
			file="CQB_Interactions\anims\anim_takendown_stand_loop.rtm";
			looped=1;
			speed=0.5;
			ConnectTo[]=
			{
				"BasicDriverDead",
				1
			};
			InterpolateTo[]=
			{
				"BasicDriverDead",
				0.1
			};
		};
		class AnimLockpickStand: default
		{
			file="CQB_Interactions\anims\anim_lockpick_stand.rtm";
			looped=0;
			speed=0.185;
			duty=2;
			mask="BodyFullReal";
			enableDirectControl=0;
			leftHandIKCurve[]={0};
			RightHandIKCurve[]={0,1,0.078947,1,0.092105001,0,0.88815802,0,0.90131599,1,1,1};
			weaponIK=0;
			forceAim=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			disableWeapons=1;
			disableWeaponsLong=1;
			headBobMode=1;
			headBobStrength=0.2;
			canPullTrigger=0;
			showHandGun=0;
			showItemInRightHand=0;
			variantsPlayer[]={};
			variantsAI[]={};
			weaponLowered=0;
		};
	};
};
class cfgMods
{
	author="kolmipilot";
	timepacked="1741020355";
};
